<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="application.tests.TestApi-20180105172646" skipped="0" tests="5" time="1.129">
	<testcase classname="application.tests.TestApi" name="test_orderRequest" time="0.910"/>
	<testcase classname="application.tests.TestApi" name="test_serializerError" time="0.047"/>
	<testcase classname="application.tests.TestApi" name="test_setApiKey" time="0.016"/>
	<testcase classname="application.tests.TestApi" name="test_worldpayError" time="0.140"/>
	<testcase classname="application.tests.TestApi" name="test_getOrderInfo" time="0.016">
		<error message="name 'requests' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "C:\Users\stylesm\Desktop\test\OFS-MORE-Beta-Secured\source\payment_gateway\application\tests.py", line 76, in test_getOrderInfo
    response = requests.get("https://api.worldpay.com/v1/orders/" +id +'?testMode=100',  headers=header)
NameError: name 'requests' is not defined
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
